CREATE TABLE IF NOT EXISTS user_expense_categories (
    id bigint generated by default as identity,
    category_name varchar(255),
    username varchar(255),
    primary key (id)
);

INSERT INTO user_expense_categories (username, category_name)
VALUES
    ('user1', 'category1'),
    ('user1', 'category2'),
    ('user1', 'category3'),
    ('user2', 'category4'),
    ('user3', 'category5'),
    ('user4', 'category6'),
    ('user5', 'category7'),
    ('user6', 'category8'),
    ('user7', 'category9'),
    ('user8', 'category10');