CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(255),
    username VARCHAR(255),
    expense_category VARCHAR(255),
    expense_date DATE,
    expense_time TIME(6),
    money_value FLOAT(53) NOT NULL
);

INSERT INTO expenses (name, description, username, expense_category, expense_date, expense_time, money_value)
VALUES
    ('Groceries', 'Weekly groceries shopping', 'john_doe', 'FOOD', '2023-07-15', '12:30:00', 75.99),
    ('Movie Tickets', 'Cinema tickets for a movie night', 'alice_wonder', 'ENTERTAINMENT', '2023-07-18', '20:15:00', 32.50),
    ('Gasoline', 'Fuel for the car', 'john_doe', 'CAR', '2023-07-15', '15:45:00', 50.00),
    ('Home Decor', 'Purchased new curtains and cushions', 'john_doe', 'HOME', '2023-07-13', '14:00:00', 120.00),
    ('Pet Food', 'Bought pet food for the month', 'pet_owner', 'ANIMALS', '2023-07-24', '18:20:00', 25.75),
    ('Gardening Supplies', 'Purchased seeds and gardening tools', 'pet_owner', 'HOBBY', '2023-07-30', '11:45:00', 40.00),
    ('Books', 'Bought some new books to read', 'pet_owner', 'EDUCATION', '2023-07-28', '16:30:00', 60.50),
    ('Kebab', '', 'john_doe', 'FOOD', '2023-04-19', '14:12:00', 10.00),
    ('Train ticket', 'Train ticket', 'alice_wonder', 'OTHER', '2021-07-18', '20:15:00', 3.50);
