CREATE TABLE IF NOT EXISTS users (
    id bigint generated by default as identity,
    email varchar(255),
    password varchar(255),
    username varchar(255),
    primary key (id)
);

INSERT INTO users(username,email,password)
VALUES
   ('username1','email1@wp.pl','password1'),
   ('username2','email2@wp.pl','password2'),
   ('username3','email3@wp.pl','password3'),
   ('username4','email4@wp.pl','password4'),
   ('username5','email5@wp.pl','password5'),
   ('username6','email6@wp.pl','password6'),
   ('username7','email7@wp.pl','password7'),
   ('username8','email8@wp.pl','password8'),
   ('username9','email9@wp.pl','password9'),
   ('username10','email10@wp.pl','password10')