CREATE TABLE expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(255),
    username VARCHAR(255),
    expense_category VARCHAR(255) CHECK (expense_category IN ('FOOD', 'HOME', 'ANIMALS', 'CAR', 'CLOTHES', 'HOBBY', 'DEBTS', 'EDUCATION', 'ENTERTAINMENT', 'OTHER')),
    date DATE,
    time TIME(6),
    money_value FLOAT(53) NOT NULL
);